name: Build GKI A12-5.10

permissions:
  contents: write
  actions: write

on:
  workflow_dispatch:
    inputs:
      # 核心功能：版本选择器
      tag_selection:
        description: "选择内核版本 (格式: 子版本 | 补丁日期 | 修订号)"
        required: true
        type: choice
        options:
          - "5.10.233 | 2025-02 | r5"
          - "5.10.226 | 2024-11 | r8"
          - "5.10.218 | 2024-08 | r14"
          - "5.10.209 | 2024-05 | r13"
          - "5.10.198 | 2024-01 | r17"
          - "Manual Input (See below)"
        default: "5.10.233 | 2025-02 | r5"
      
      # 手动输入覆盖（可选）
      manual_version:
        description: "手动输入(仅当上方选Manual时生效, 格式: 5.10.xxx 20xx-xx rxx)"
        required: false
        type: string

      kernelsu_variant:
        description: "选择 KernelSU 变体"
        required: true
        type: choice
        options:
          - ReSukiSU
          - SukiSU
          - Official
          - MKSU
        default: ReSukiSU
      kernelsu_branch:
        description: "选择 ksu 分支"
        required: true
        type: choice
        options:
          - Stable(标准)
          - Dev(开发)
          - tmp-builtin
        default: Stable(标准)
      use_zram:
        description: '开启 ZRAM 优化 (LZ4)?'
        required: true
        type: boolean
        default: true
      use_bbg:
        description: '开启 BBG 防格机?'
        required: true
        type: boolean
        default: true
      use_kpm:
        description: '开启 KPM?'
        required: true
        type: boolean
        default: true
      cancel_susfs:
        description: '取消 SUSFS'
        required: true
        type: boolean
        default: false
      onlyAk3:
        description: '仅上传 AK3 (不打包 boot.img)?'
        required: false
        type: boolean
        default: false

jobs:
  build-kernel:
    runs-on: ubuntu-latest
    env:
      ANDROID_VERSION: "android12"
      KERNEL_VERSION: "5.10"
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"

    steps:
      - name: Maximize Build Space
        uses: AdityaGarg8/remove-unwanted-software@v5
        with:
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          verbose: 'false'

      - name: Checkout repository
        uses: actions/checkout@v4

      # ========================================================
      # 核心步骤：解析用户选择的版本
      # ========================================================
      - name: 解析版本参数
        run: |
          # 获取输入
          SELECTION="${{ inputs.tag_selection }}"
          MANUAL="${{ inputs.manual_version }}"
          
          # 判断是否使用手动输入
          if [[ "$SELECTION" == "Manual Input"* ]] && [[ -n "$MANUAL" ]]; then
            echo "使用手动输入的版本: $MANUAL"
            # 假设手动格式为空格分隔: 5.10.233 2025-02 r5
            SUB_LEVEL=$(echo "$MANUAL" | awk '{print $1}' | cut -d. -f3)
            OS_PATCH=$(echo "$MANUAL" | awk '{print $2}')
            REV=$(echo "$MANUAL" | awk '{print $3}')
          else
            echo "使用预设版本: $SELECTION"
            # 预设格式: "5.10.233 | 2025-02 | r5"
            # awk $1=5.10.233, $3=2025-02, $5=r5 (因为 | 也是分隔符)
            SUB_LEVEL=$(echo "$SELECTION" | awk -F' | ' '{print $1}' | cut -d. -f3)
            # 处理 awk 分割可能存在的空格问题，这里使用更稳健的 cut
            # 原始串: 5.10.233 | 2025-02 | r5
            OS_PATCH=$(echo "$SELECTION" | cut -d'|' -f2 | xargs) # xargs 去除首尾空格
            REV=$(echo "$SELECTION" | cut -d'|' -f3 | xargs)
          fi

          echo "解析结果:"
          echo "  Sub Level: $SUB_LEVEL"
          echo "  Patch: $OS_PATCH"
          echo "  Revision: $REV"

          # 写入环境变量供后续步骤使用
          echo "SUB_LEVEL=$SUB_LEVEL" >> $GITHUB_ENV
          echo "OS_PATCH_LEVEL=$OS_PATCH" >> $GITHUB_ENV
          echo "REVISION=$REV" >> $GITHUB_ENV
          echo "CONFIG=android12-5.10-$SUB_LEVEL" >> $GITHUB_ENV

      - name: 安装构建依赖
        run: sudo apt update && sudo apt install -y ccache python3 git curl build-essential libssl-dev bison flex libelf-dev dwarves

      - name: 下载工具链
        run: |
          mkdir -p ./git-repo
          curl https://storage.googleapis.com/git-repo-downloads/repo > ./git-repo/repo
          chmod a+rx ./git-repo/repo
          echo "REPO=$GITHUB_WORKSPACE/git-repo/repo" >> $GITHUB_ENV
          
          AOSP_MIRROR=https://android.googlesource.com
          BRANCH=main-kernel-build-2024
          git clone $AOSP_MIRROR/kernel/prebuilts/build-tools -b $BRANCH --depth 1 kernel-build-tools
          git clone $AOSP_MIRROR/platform/system/tools/mkbootimg -b $BRANCH --depth 1 mkbootimg
          
          echo "MKBOOTIMG=$GITHUB_WORKSPACE/mkbootimg/mkbootimg.py" >> $GITHUB_ENV
          echo "UNPACK_BOOTIMG=$GITHUB_WORKSPACE/mkbootimg/unpack_bootimg.py" >> $GITHUB_ENV
          echo "AVBTOOL=$GITHUB_WORKSPACE/kernel-build-tools/linux-x86/bin/avbtool" >> $GITHUB_ENV
          
          # 生成签名Key
          openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:2048 > ./kernel-build-tools/linux-x86/share/avb/testkey_rsa2048.pem
          echo "BOOT_SIGN_KEY_PATH=$GITHUB_WORKSPACE/kernel-build-tools/linux-x86/share/avb/testkey_rsa2048.pem" >> $GITHUB_ENV

      - name: 克隆辅助仓库
        run: |
          git clone https://github.com/WildPlusKernel/AnyKernel3.git -b "gki-2.0"
          git clone https://github.com/zzh20188/GKI_KernelSU_SUSFS.git zzh_patch
          git clone https://github.com/Numbersf/Action-Build.git --depth=1
          
          # 选择 SUSFS 仓库
          if [ "${{ inputs.kernelsu_variant }}" == "SukiSU" ] || [ "${{ inputs.kernelsu_variant }}" == "ReSukiSU" ]; then
            git clone https://github.com/ShirkNeko/susfs4ksu.git -b "gki-${{ env.ANDROID_VERSION }}-${{ env.KERNEL_VERSION }}"
          else
            git clone https://gitlab.com/simonpunk/susfs4ksu.git -b "gki-${{ env.ANDROID_VERSION }}-${{ env.KERNEL_VERSION }}"
          fi

      - name: 同步内核源码
        run: |
          mkdir -p "$CONFIG"
          cd "$CONFIG"
          git clone https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-gnu-6.4.1.git gcc

          # 构建 Manifest 分支名
          # 格式通常为: common-android12-5.10-YYYY-MM
          MANIFEST_BRANCH="common-${{ env.ANDROID_VERSION }}-${{ env.KERNEL_VERSION }}-${{ env.OS_PATCH_LEVEL }}"
          
          echo "正在同步分支: $MANIFEST_BRANCH"
          
          # 初始化 (移除 --no-tags 以修复版本号生成)
          $REPO init --depth=1 -u https://android.googlesource.com/kernel/manifest -b $MANIFEST_BRANCH --repo-rev=v2.16
          
          # 如果同步失败(比如Google还没发布这个月的Tag)，尝试回退到通用的 android12-5.10 分支
          if ! $REPO sync -c -j$(nproc --all) --fail-fast; then
             echo "错误: 无法同步分支 $MANIFEST_BRANCH，尝试同步通用分支..."
             $REPO init --depth=1 -u https://android.googlesource.com/kernel/manifest -b common-${{ env.ANDROID_VERSION }}-${{ env.KERNEL_VERSION }}
             $REPO sync -c -j$(nproc --all) --fail-fast
          fi

      - name: 确定 KernelSU 参数
        run: |
          VAR="${{ inputs.kernelsu_variant }}"
          BR="${{ inputs.kernelsu_branch }}"
          ARG=""
          
          if [ "$BR" == "tmp-builtin" ]; then
             ARG="-s tmp-builtin"
          elif [ "$BR" == "Stable(标准)" ]; then
             if [[ "$VAR" == "SukiSU" || "$VAR" == "ReSukiSU" ]]; then ARG="-s builtin"; else ARG="-s stable"; fi
          elif [ "$BR" == "Dev(开发)" ]; then
             if [[ "$VAR" == "SukiSU" || "$VAR" == "ReSukiSU" ]]; then ARG="-s tmp-builtin"; else ARG="-s main"; fi
          fi
          
          echo "KSU_ARGS=$ARG" >> $GITHUB_ENV

      - name: 注入 Kernel
